name: ETL Pipeline

on:
  # # Comment out the cron job to stop the automated schedule
  # schedule:
  #   - cron: "0 * * * *"  # Run every hour

  # # Comment out or remove the manual trigger as well
  # workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  run-etl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run ETL Script
        run: |
          python etl.py
